name: fifty_theme
description: Flutter theming layer for the fifty.dev ecosystem.
version: 1.0.0
homepage: https://fifty.dev
repository: https://github.com/fiftynotai/fifty_theme

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.0.0'

dependencies:
  flutter:
    sdk: flutter
  fifty_tokens:
    path: ../fifty_tokens
  google_fonts: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
