name: fifty_speech_engine
description: "Fifty ecosystem speech engine - TTS and STT for Flutter games and applications"
version: 0.1.0
homepage: https://github.com/fiftynotai/fifty_eco_system
repository: https://github.com/fiftynotai/fifty_eco_system/tree/main/packages/fifty_speech_engine

environment:
  sdk: ^3.6.0
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  web: ^1.0.0
  plugin_platform_interface: ^2.0.2
  speech_to_text: ^7.1.0
  flutter_tts: ^4.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.fifty.speech_engine
        pluginClass: FiftySpeechEnginePlugin
      ios:
        pluginClass: FiftySpeechEnginePlugin
      linux:
        pluginClass: FiftySpeechEnginePlugin
      web:
        pluginClass: FiftySpeechEngineWeb
        fileName: fifty_speech_engine_web.dart
