name: fifty_speech_engine
description: "Fifty Flutter Kit speech engine - TTS and STT for Flutter games and applications"
version: 0.2.0
homepage: https://fifty.dev
repository: https://github.com/fiftynotai/fifty_flutter_kit/tree/main/packages/fifty_speech_engine
issue_tracker: https://github.com/fiftynotai/fifty_flutter_kit/issues
topics:
  - flutter
  - speech
  - tts
  - stt
screenshots:
  - description: 'Speech-to-text panel'
    path: screenshots/stt_panel_light.png
  - description: 'Text-to-speech panel'
    path: screenshots/tts_panel_light.png

environment:
  sdk: ^3.6.0
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  web: ^1.0.0
  plugin_platform_interface: ^2.0.2
  speech_to_text: ^7.1.0
  flutter_tts: ^4.2.3

  # FDL Foundation (for widgets)
  fifty_tokens:
    path: ../fifty_tokens
  fifty_theme:
    path: ../fifty_theme
  fifty_ui:
    path: ../fifty_ui

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.fifty.speech_engine
        pluginClass: FiftySpeechEnginePlugin
      ios:
        pluginClass: FiftySpeechEnginePlugin
      linux:
        pluginClass: FiftySpeechEnginePlugin
      web:
        pluginClass: FiftySpeechEngineWeb
        fileName: fifty_speech_engine_web.dart
