name: fifty_audio_engine
description: "Fifty Flutter Kit audio engine - modular and reactive audio system for Flutter"
version: 0.7.2
homepage: https://fifty.dev
repository: https://github.com/fiftynotai/fifty_flutter_kit/tree/main/packages/fifty_audio_engine
issue_tracker: https://github.com/fiftynotai/fifty_flutter_kit/issues
topics:
  - flutter
  - audio
  - game
  - engine
screenshots:
  - description: 'Background music player'
    path: screenshots/bgm_player_light.png
  - description: 'Global audio controls'
    path: screenshots/global_controls_light.png
  - description: 'Sound effects player'
    path: screenshots/sfx_player_light.png
  - description: 'Voice channel player'
    path: screenshots/voice_player_light.png

environment:
  sdk: ^3.6.0
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  audioplayers: ^6.4.0
  get_storage: ^2.1.1
  fifty_tokens:
    path: ../fifty_tokens
  fifty_theme:
    path: ../fifty_theme
  fifty_ui:
    path: ../fifty_ui
  flutter_web_plugins:
    sdk: flutter
  plugin_platform_interface: ^2.0.2
  web: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  plugin:
    platforms:
      android:
        package: dev.fifty.audio_engine
        pluginClass: FiftyAudioEnginePlugin
      ios:
        pluginClass: FiftyAudioEnginePlugin
      linux:
        pluginClass: FiftyAudioEnginePlugin
      macos:
        pluginClass: FiftyAudioEnginePlugin
      windows:
        pluginClass: FiftyAudioEnginePluginCApi
      web:
        pluginClass: FiftyAudioEngineWeb
        fileName: fifty_audio_engine_web.dart
