name: fifty_skill_tree_example
description: Example app demonstrating fifty_skill_tree package.
publish_to: 'none'
version: 1.0.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  fifty_skill_tree:
    path: ../
  fifty_tokens:
    path: ../../fifty_tokens
  fifty_ui:
    path: ../../fifty_ui
  fifty_theme:
    path: ../../fifty_theme

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
