name: fifty_ui
description: FDL v2 styled Flutter components for the fifty.dev ecosystem.
version: 0.6.0
publish_to: none
homepage: https://fifty.dev
repository: https://github.com/fiftynotai/fifty_flutter_kit

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.0.0'

dependencies:
  flutter:
    sdk: flutter
  fifty_tokens:
    path: ../fifty_tokens
  fifty_theme:
    path: ../fifty_theme
  flutter_animate: ^4.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
