name: fifty_world_engine_example
description: "FDL Tactical Grid Demo - fifty_world_engine showcase"
publish_to: 'none'

environment:
  sdk: ^3.6.0
  flutter: '>=3.0.0'

dependencies:
  flutter:
    sdk: flutter
  fifty_world_engine:
    path: ../
  fifty_tokens:
    path: ../../fifty_tokens
  fifty_theme:
    path: ../../fifty_theme

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/units/
    - assets/images/tiles/
