name: fifty_connectivity_example
description: Example app demonstrating fifty_connectivity package usage
version: 1.0.0
publish_to: 'none'

environment:
  sdk: ^3.6.0
  flutter: '>=3.10.0'

dependencies:
  flutter:
    sdk: flutter
  fifty_connectivity:
    path: ../
  fifty_theme:
    path: ../../fifty_theme
  fifty_tokens:
    path: ../../fifty_tokens
  fifty_ui:
    path: ../../fifty_ui
  get: ^4.6.6
  connectivity_plus: ^6.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
