name: fifty_ui_example
description: Example gallery app demonstrating fifty_ui components.
publish_to: none

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.0.0'

dependencies:
  flutter:
    sdk: flutter
  fifty_ui:
    path: ../
  fifty_theme:
    path: ../../fifty_theme
  fifty_tokens:
    path: ../../fifty_tokens

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
