name: fifty_sentences_engine
description: "Fifty ecosystem sentence processing engine for games and interactive applications"
version: 0.1.0
homepage: https://github.com/fiftynotai/fifty_eco_system
repository: https://github.com/fiftynotai/fifty_eco_system/tree/main/packages/fifty_sentences_engine

environment:
  sdk: ^3.6.0
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  web: ^1.0.0
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.fifty.sentences_engine
        pluginClass: FiftySentencesEnginePlugin
      ios:
        pluginClass: FiftySentencesEnginePlugin
      linux:
        pluginClass: FiftySentencesEnginePlugin
      macos:
        pluginClass: FiftySentencesEnginePlugin
      windows:
        pluginClass: FiftySentencesEnginePluginCApi
      web:
        pluginClass: FiftySentencesEngineWeb
        fileName: fifty_sentences_engine_web.dart
